language: node_js

node_js:
  - "10.14.1"

sudo: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE db_wtraining_test;" -U postgres

steps:
  test:
    - npm run test

env:
  - CXX=g++-4.8 NODE_ENV=testing